config:

  general:
    name: vae-kl-f8-rmse-disc

  data:
    x: 1440
    y: 720
    in_channels: 69
    out_channels: 69

  dataloader:
    num_workers: 32

  model:
    z_channels: 64
    embed_dim: 64
    channels: 128
    channel_mult: [1, 2, 4, 4]
    num_res_blocks: 2
    norm_groups: 32
    attention: True
    num_heads: 4

  loss:
    reconstruction_loss: rmse
    kl_weight: 0.000001
    discriminator_weight: 0.01
    discriminator_start_steps: 100000

  training:
    learning_rate: 0.00001
    epochs: 10
    batch_size: 1
    lr_scheduler: None