config:

  general:
    name: vqvae-f16

  data:
    x: 1440
    y: 720
    in_channels: 69
    out_channels: 69

  dataloader:
    num_workers: 32

  model:
    z_channels: 64
    embed_dim: 64
    channels: 128
    channel_mult: [1, 2, 2, 4, 4]
    num_res_blocks: 2
    norm_groups: 32
    attention: True
    num_heads: 4
    codebook_size: 8192
    commitment_beta: 0.5

  loss:
    reconstruction_loss: rmse
    discriminator_weight: 0.0
    discriminator_start_steps: 0

  training:
    learning_rate: 0.000005
    epochs: 10
    batch_size: 1
    lr_scheduler: None


